sudo: false
language: python
python:
  - 3.4
  - 3.5
  - 3.6

cache:
  pip: true
  directories:
    - node_modules

os:
#  # The macOS build in travis is really slow.
#  - osx
  - linux

# Note that in order to run the tests on Linux, 
# you need to have a before_install configuration 
# to enable Linux to start VS Code from the build.
# ref https://code.visualstudio.com/Docs/extensions/testing-extensions
before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

before_script:
  # nltk 3.2.2 dropped support for Python 3.3
  - >
    if [[ "$TRAVIS_PYTHON_VERSION" != "3.3" ]]; then
      python -m nltk.downloader punkt maxent_treebank_pos_tagger averaged_perceptron_tagger
    fi

install:
  # beheve is a dev dependeny, so not in requirements.txt.
  - pip install behave
  - pip install -r ./requirements.txt
  # codecov is a code coverage tool.
  - pip install codecov
  - cd ./vscode-client
  - npm install
  - mkdir ./out
  - npm run vscode:prepublish
  - cd - > /dev/null

script:
  # Server side tests.
  - coverage run $(which behave) ./tests/server.features
#  # Integration tests.
#  - cd ./vscode-client
#  - npm test
#  - cd - > /dev/null

after_success:
  - codecov
#  # If the build was triggered by a tag, publish the new version
#  - 'if [[ $TRAVIS_TAG == v* ]]; then vsce publish -p $VSCE_TOKEN; fi'
